AWSTemplateFormatVersion: 2010-09-09
Description: Playground Template

Resources:
  #VPC
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: CF
  #Internet Gateway
  igwName:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CF
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: myVPC
      InternetGatewayId:
        Ref: igwName
  
  #Subnets
  subnetName1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1a"
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: CF-Pub-1
  subnetName2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "us-east-1b"
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: CF-Pub-2
  
  #route tables
  routeTableName:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: myVPC
      Tags:
        - Key: Name
          Value: CF-Pub-RT

  routeTableAssocName1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: subnetName1
      RouteTableId:
        Ref: routeTableName

  routeTableAssocName2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: subnetName2
      RouteTableId:
        Ref: routeTableName

  routeName:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: routeTableName
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: igwName

  #ACL
  publicACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: myVPC
      Tags:
      - Key: Name
        Value: CF

  sshACLIn:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: publicACL
      RuleNumber: '100'
      Protocol: "6"
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      Icmp:
        Code: "-1"
        Type: "-1"
      PortRange:
        From: '22'
        To: '22'

  httpACLIn:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: publicACL
      RuleNumber: '200'
      Protocol: "6"
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      Icmp:
        Code: "-1"
        Type: "-1"
      PortRange:
        From: '80'
        To: '80'

  sshACLOut:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: publicACL
      RuleNumber: '100'
      Protocol: "6"
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      Egress: true
      Icmp:
        Code: "-1"
        Type: "-1"
      PortRange:
        From: '22'
        To: '22'

  httpACLOut:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId:
        Ref: publicACL
      RuleNumber: '200'
      Protocol: "6"
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      Egress: true
      Icmp:
        Code: "-1"
        Type: "-1"
      PortRange:
        From: '80'
        To: '80'

  #Security Group
  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: myVPC
      GroupDescription: http port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80 
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: CF


Outputs:
  SecurityGroup:
    Description: Security Group ID
    Value:
      Ref: secGroupName
    Export: 
      Name: Netowrk-SecurityGroup

  Subnet1:
    Description: Subnet 1 of the stack
    Value:
      Ref: subnetName1
    Export: 
      Name: Network-Subnet1